# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class A8 < Formula
  desc "a8 - autom8y ecosystem control plane CLI"
  homepage "https://github.com/autom8y/a8"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autom8y/a8/releases/download/v0.1.2/a8_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "20d57f5d5fe95fdf5032178845330a0e5bc9cb3ea089773b58bbadc6a43dfa89"

      define_method(:install) do
        bin.install "a8"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autom8y/a8/releases/download/v0.1.2/a8_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0fd2d1f3cc77d1d1c5d5748c51e419649fe9dba09606e1a904c3ed20fe4725a5"

      define_method(:install) do
        bin.install "a8"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/autom8y/a8/releases/download/v0.1.2/a8_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "25f80848a718d842ad05ebf11d46d76b52eb96f305cd16d39138e54d25537f4b"
      define_method(:install) do
        bin.install "a8"
      end
    end
  end

  test do
    system "#{bin}/a8", "--help"
  end
end
