# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class A8 < Formula
  desc "a8 - autom8y ecosystem control plane CLI"
  homepage "https://github.com/autom8y/a8"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autom8y/a8/releases/download/v0.1.1/a8_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "172bc1d22fe4bf69143c37c6ed7b9e556ae5b9a908d6cb50dee8d3d988311079"

      define_method(:install) do
        bin.install "a8"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autom8y/a8/releases/download/v0.1.1/a8_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2c9538e54440f3db00a289749d224f66fec618291c1d78f1efc6463f0e0d42ab"

      define_method(:install) do
        bin.install "a8"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/autom8y/a8/releases/download/v0.1.1/a8_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "34717ca6ce5e926783dcc53f39212715359d0440ac2ec7e355d696b23d042c8e"
      define_method(:install) do
        bin.install "a8"
      end
    end
  end

  test do
    system "#{bin}/a8", "--help"
  end
end
