# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ari < Formula
  desc "Ariadne CLI - The thread through the Knossos labyrinth"
  homepage "https://github.com/autom8y/knossos"
  version "0.3.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autom8y/knossos/releases/download/v0.3.11/ari_0.3.11_darwin_amd64.tar.gz"
      sha256 "4915dc436abe239e1554cb4cce101379885437ba7d88f007822587aa33ef9575"

      define_method(:install) do
        bin.install "ari"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autom8y/knossos/releases/download/v0.3.11/ari_0.3.11_darwin_arm64.tar.gz"
      sha256 "75094ffcad41a14b1584bd695436c308e0db43eefbf2288dcb6b807973b210ae"

      define_method(:install) do
        bin.install "ari"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/autom8y/knossos/releases/download/v0.3.11/ari_0.3.11_linux_amd64.tar.gz"
      sha256 "0134dbca45a8eb774f47fbb089486d9ef945ae96e799e13968e365fc7b649eaa"
      define_method(:install) do
        bin.install "ari"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/autom8y/knossos/releases/download/v0.3.11/ari_0.3.11_linux_arm64.tar.gz"
      sha256 "12203e701cceca953b873d73a547947dc2e2dfb1ccc285efc2ee4d145ca72bfc"
      define_method(:install) do
        bin.install "ari"
      end
    end
  end

  test do
    system "#{bin}/ari", "--help"
  end
end
